### ISSUE TITLE
tun2socks-rs

### ISSUE THREAD

**Issue by TongxiJi** [eycorsican/tun2socks-ios#1]
tun2socks-rs咋被删除了？我还想看看源码来着。

**Comment by ssrlive** [comment]
这里有forks，希望楼主或作者再接再厉，完善这个版本。

https://github.com/kennethgao/tun2socks-rs

https://github.com/sayhell/lwip-tun2socks

**Comment by TongxiJi** [comment]
@ssrlive  老铁有心了,谢谢🐦.
